name: Articler CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint source code
        run: yarn lint

  audit-deps:
    name: Audit dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run dependencies audit
        run: yarn npm audit --all

  audit-code:
    name: Audit source code
    runs-on: ubuntu-22.04
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run semgrep scan
        run: ./bin/run-semgrep.sh
